### ISSUE TITLE
Can't compile templates - *.jst returns [object Promise]

### ISSUE THREAD

**Issue by me-cooper** [benchpressjs/benchpressjs#105]
Hello!

If I try to compile to just test with the following code from original repo:

```js
const fs = require('fs').promises;
const benchpress = require('benchpressjs');

const template = await fs.readFile('templates/index.tpl', 'utf8');
const compiled = benchpress.precompile(template, { filename: 'index.tpl' });
await fs.writeFile('compiled/templates/index.jst', compiled);
```

It drops an error:

```
Users-Air-6:express-with-templates user$ node compile.js 
/Users/user/Desktop/playing-around/express-with-templates/compile.js:4
const template = await fs.readFile('templates/index.tpl', 'utf8');
                 ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

---

So i tried it with an async function:

```js
const fs = require('fs').promises;
const benchpress = require('benchpressjs');
  
async function compileTemplate(filename, source) {
	const template = await fs.readFile('templates/' + source, 'utf8');
    const compiled = benchpress.precompile(template, { filename: source });
    await fs.writeFile('compiled/templates/' + filename, compiled);
}

compileTemplate("index.jst","index.tpl");
```

Which drops no error. But the index.jst file returns just following:

```js
[object Promise]
```

The template I want to compile looks as following:

```html
<p>Hello! I am {foo}! How are you?</p>
```

---

Did I miss anything? Did I do anyhing wrong? Any help would be awesome :)

**Comment by me-cooper** [comment]
I edited

```js
async function compileTemplate(filename, source) {
	const template = await fs.readFile('templates/' + source, 'utf8');
        const compiled = benchpress.precompile(template, { filename: source });
        await fs.writeFile('compiled/templates/' + filename, compiled);
}
```

to 

```js
async function compileTemplate(filename, source) {
	const template = await fs.readFile('templates/' + source, 'utf8');
        const compiled = await benchpress.precompile(template, { filename: source });
        await fs.writeFile('compiled/templates/' + filename, compiled);
}
```

now it works! :) ** index.jst**

```js

(function (factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else if (typeof define === 'function' && define.amd) {
    define(factory);
  }
})(function () {
  function compiled(helpers, context, guard, iter, helper) {
    var __escape = helpers.__escape;
    var value = context;
    return "<p>Hello! I am " + 
      __escape(guard(context && context['foo'])) + 
      "! How are you?</p>";
  }

  compiled.blocks = {
    
  };

  return compiled;
})

```

**Comment by pitaj** [comment]
I fixed the readme
