### ISSUE TITLE
Compile / build problem

### ISSUE THREAD

**Issue by youhosi** [benchpressjs/benchpressjs#83]
System: macOS 10.14.3
NodeBB version: 1.12.0
Node version: 10.15.2

Hello, I have a problem while building a style (nodebb-theme-oxide). What is the problem, or could I get some tips? It is quite a nuisance for me because the persona style normally works.

Logs:

``` bash
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version

...

2019-03-11T09:09:36.891Z [4567/17443] - error: [build]                  templates  build failed
2019-03-11T09:09:36.892Z [4567/17443] - error: [build] Encountered error during build stepProperty consequent of ConditionalExpression expected node to be of a type ["Expression"] but instead got null {"stack":"TypeError: Property consequent of ConditionalExpression expected node to be of a type [\"Expression\"] but instead got null\n    at Object.validate (/Users/youhosi/Desktop/NodeBB/node_modules/babel-types/lib/definitions/index.js:109:13)\n    at validate (/Users/youhosi/Desktop/NodeBB/node_modules/babel-types/lib/index.js:505:9)\n    at Object.builder (/Users/youhosi/Desktop/NodeBB/node_modules/babel-types/lib/index.js:466:7)\n    at Object.OpenIf (/Users/youhosi/Desktop/NodeBB/node_modules/benchpressjs/build/lib/compiler/compiler.js:115:14)\n    at compile (/Users/youhosi/Desktop/NodeBB/node_modules/benchpressjs/build/lib/compiler/compiler.js:160:49)\n    at Object.OpenIter (/Users/youhosi/Desktop/NodeBB/node_modules/benchpressjs/build/lib/compiler/compiler.js:127:246)\n    at compile (/Users/youhosi/Desktop/NodeBB/node_modules/benchpressjs/build/lib/compiler/compiler.js:160:49)\n    at compiler (/Users/youhosi/Desktop/NodeBB/node_modules/benchpressjs/build/lib/compiler/compiler.js:175:20)\n    at compileFallback (/Users/youhosi/Desktop/NodeBB/node_modules/benchpressjs/build/lib/precompile.js:37:17)\n    at Promise.try (/Users/youhosi/Desktop/NodeBB/node_modules/benchpressjs/build/lib/precompile.js:103:88)"}

```

**Comment by pitaj** [comment]
Can you place a new line
```
console.log('error filepath': filePath);
```

Before the following line: https://github.com/NodeBB/NodeBB/blob/master/src/meta/templates.js#L185

This will allow you to find out what template is causing this issue. Please paste the contents of that template here and I'll fix the issue and add it as an integration test for the future.

**Comment by youhosi** [comment]
@pitaj Thank you, it worked. If you can add this to benchpressjs, it will definitely be useful :)

**Comment by pitaj** [comment]
Please provide the template that was causing the issue. Benchpress should never error during compile: any invalid template syntax should be ignored.

**Comment by pitaj** [comment]
Okay I found it, I'll fix the issue and add it as a test.

```html
<ul component="posts" class="posts posts-list" data-nextstart="{nextStart}">

	<!-- BEGIN posts -->
	<li component="post" class="posts-list-item <!-- IF posts.deleted --> deleted<!-- ELSE --><!-- IF posts.topic.deleted --> deleted<!-- ENDIF posts.topic.deleted --><!-- ENDIF posts.deleted -->" data-pid="{posts.pid}" data-uid="{posts.uid}">
		<div class="post-body">
			<div class="clearfix post-header">
				<div class="icon pull-left">
					<a href="{config.relative_path}/user/{posts.user.userslug}">
						<!-- IF posts.user.picture -->
						<img title="{posts.user.username}" class="img-rounded user-img" src="{posts.user.picture}">
						<!-- ELSE -->
						<div class="user-icon user-img" style="background-color: {posts.user.icon:bgColor};" title="{posts.user.username}">{posts.user.icon:text}</div>
						<!-- ENDIF posts.user.picture -->
					</a>
				</div>
			</div>

			<div class="post-body content">
				<div class="post-author">
					<strong>
						<a class="topic-title" href="{config.relative_path}/post/{posts.pid}"><!-- IF !posts.isMainPost --><!-- ENDIF !posts.isMainPost -->{posts.topic.title}</a>
					</strong>

					<span class="permalink timeago" title="{posts.timestampISO}"></span>
				</div>

				<div component="post/content">
					{posts.content}
				</div>
			</div>

			<a class="topic-category" href="{config.relative_path}/category/{posts.category.slug}">
				[[global:posted_in, {posts.category.name}]]
			</a>
		</div>
	</li>
	<!-- END posts -->
</ul>

<div component="posts/loading" class="loading-indicator text-center hidden">
	<i class="fa fa-refresh fa-spin"></i>
</div>
```

Seems like the main culprit is the empty body of the IF...ENDIF
