### ISSUE TITLE
MacOS 10.15 can't build rust build

### ISSUE THREAD

**Issue by jedimonkey** [benchpressjs/benchpressjs#86]
Trying to build the benchpress-rs when installing benchpressjs and it fails to build the binary, reverting to compiling with js.

Versions installed:
rustc - 1.42.0 (installed via homebrew)
python - 2.7.16
neon - 0.4.0
npm - 6.14.4
node - 12.16.2 (tried latest 8, 10 & 12)

build.log:
```
neon info forcing rebuild for new build settings
neon info running cargo
   Compiling memchr v2.3.2
   Compiling lazy_static v1.4.0
   Compiling regex-syntax v0.6.14
   Compiling cc v1.0.41
   Compiling neon-build v0.3.1
   Compiling either v1.5.0
   Compiling semver-parser v0.7.0
   Compiling json v0.12.1
   Compiling cslice v0.2.0
   Compiling thread_local v1.0.1
   Compiling neon v0.3.1
   Compiling benchpress-rs v0.1.0 (/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native)
   Compiling itertools v0.8.2
   Compiling semver v0.9.0
   Compiling aho-corasick v0.7.8
   Compiling regex v1.3.4
   Compiling benchpress_sys v0.1.0 (/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/benchpress_sys)
   Compiling neon-runtime v0.3.1
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.0.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.1.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.10.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.11.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.12.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.13.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.14.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.15.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.2.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.3.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.4.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.5.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.6.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.7.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.8.rcgu.o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.benchpress_rs.77rml78k-cgu.9.rcgu.o" "-o" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libbenchpress_rs.dylib" "-Wl,-exported_symbols_list,/var/folders/zd/82jnxxpj5gbgjfp6lggy_lz5xn0_6q/T/rustcESSCHP/list" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/benchpress_rs.4oylf5bnuuwul4hh.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps" "-L" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/build/neon-runtime-07ef246a1c1568ef/out" "-L" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libneon-a1255b6689a3c43e.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libsemver-fe190c1b53367c4d.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libsemver_parser-ce1d91984306bc84.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libcslice-ed3d084ca559ddda.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libneon_runtime-c2aaf52cfe0ee31d.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libbenchpress_sys-1fc9abcecb084a85.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libjson-edded06a7f6eab27.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libitertools-fd4785c8b0b42838.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libeither-29de4c47020026c4.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libregex-8931f2639ad314c6.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libthread_local-9c739dbc1c9762c7.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libregex_syntax-435b53b814759f9e.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libaho_corasick-1ef26f493bcb73c7.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/libmemchr-0114f282056375bc.rlib" "/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/native/target/release/deps/liblazy_static-40a8dbb5a45d4dfc.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/libstd-5ac8d8d4e885e7ea.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-31a317cba2ea608f.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-e663228b3a72c3b4.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-c3e3d519896c561c.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace-00000d459680f741.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace_sys-330d49dc0aa2c735.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-11aa2caed781b665.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/libunwind-96408568c54b6ec7.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-7040b9a0b1863285.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/liblibc-fc91fd6650ffc137.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/liballoc-ad887e9bb97552e0.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-eeb8c307d85bc5f1.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/libcore-e7605d10d7a7abee.rlib" "/usr/local/Cellar/rust/1.42.0/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-4acd3cb9a43668af.rlib" "-lSystem" "-lresolv" "-lc" "-lm" "-dynamiclib" "-Wl,-dylib"
  = note: Undefined symbols for architecture x86_64:
            "v8::External::New(v8::Isolate*, void*)", referenced from:
                _Neon_Fun_New in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::Function::New(v8::Local<v8::Context>, void (*)(v8::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)", referenced from:
                _Neon_Fun_New in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::EscapableHandleScope::EscapableHandleScope(v8::Isolate*)", referenced from:
                _Neon_Convert_ToString in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::V8::ToLocalEmpty()", referenced from:
                _Neon_Error_ThrowErrorFromUtf8 in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::EscapableHandleScope::Escape(unsigned long*)", referenced from:
                _Neon_Convert_ToString in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::Value::ToString(v8::Local<v8::Context>) const", referenced from:
                _Neon_Convert_ToString in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::String::Utf8Length(v8::Isolate*) const", referenced from:
                _Neon_String_Utf8Length in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "node::DecodeWrite(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding)", referenced from:
                _Neon_String_Data in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int)", referenced from:
                _Neon_Object_Set_String in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_String_New in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Error_ThrowErrorFromUtf8 in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::Exception::TypeError(v8::Local<v8::String>)", referenced from:
                _Neon_Error_NewTypeError in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::HandleScope::HandleScope(v8::Isolate*)", referenced from:
                _Neon_Object_Set_String in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Scope_Enter in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Error_ThrowErrorFromUtf8 in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::Isolate::GetCurrentContext()", referenced from:
                _Neon_Object_Set_String in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Convert_ToString in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Fun_New in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::Exception::Error(v8::Local<v8::String>)", referenced from:
                _Neon_Error_ThrowErrorFromUtf8 in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)", referenced from:
                _Neon_Object_Set_String in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::External::Value() const", referenced from:
                _Neon_Fun_GetDynamicCallback in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::HandleScope::~HandleScope()", referenced from:
                _Neon_Object_Set_String in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Scope_Exit in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Error_ThrowErrorFromUtf8 in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::Isolate::ThrowException(v8::Local<v8::Value>)", referenced from:
                _Neon_Error_Throw in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Error_ThrowErrorFromUtf8 in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::HandleScope::~HandleScope()", referenced from:
                _Neon_Convert_ToString in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
            "v8::Isolate::GetCurrent()", referenced from:
                _Neon_Call_CurrentIsolate in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Object_Set_String in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_String_Utf8Length in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_String_Data in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Convert_ToString in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Error_Throw in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                _Neon_Error_ThrowErrorFromUtf8 in libneon_runtime-c2aaf52cfe0ee31d.rlib(neon.o)
                ...
            "_node_module_register", referenced from:
                benchpress_rs::__LOAD_NEON_MODULE::__load_neon_module::h8cdba572bd1997c7 in benchpress_rs.benchpress_rs.77rml78k-cgu.4.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: could not compile `benchpress-rs`.

To learn more, run the command again with --verbose.
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/node_modules/neon-cli/lib/target.js:121:35)
    at step (/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/path/to/nodebb/node_modules/benchpressjs/rust/benchpress-rs/node_modules/neon-cli/lib/target.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I'm out of ideas what to change to get it to build as I've tried uninstalling/reinstalling rust/node/neon to multiple different versions.

**Comment by greg-n** [comment]
I had the same issue with the literally the exact same setup. I think the issue is with the crate versions for `neon-build` and `neon`. Upgrading the versions of both fixed the compilation error (upgrade to at least `0.3.3` I think). It might be related to [this issue.](https://github.com/neon-bindings/neon/issues/455)

**Comment by jedimonkey** [comment]
I managed to get this working earlier today. I hacked the Cargo.toml file in the benchpress-rs/native folder and updated `[build-dependancies]` for `neon-build` to 0.4.0. It compiles okay now.
When you say 'upgrading' do you mean upgrading neon tools? as that was already @ 0.4.0. Or do you mean upgrading the library similar to my modifications?

I also updated the `[dependancies]` for `neon` to 0.4.0 although that seemed more logical to keep them in the same version, but it worked without that modification either way.

**Comment by greg-n** [comment]
Oh nice. Yeah meant the crate versions in the toml file specifically.

**Comment by jedimonkey** [comment]
> I had the same issue with the literally the exact same setup. I think the issue is with the crate versions for `neon-build` and `neon`. Upgrading the versions of both fixed the compilation error (upgrade to at least `0.3.3` I think). It might be related to [this issue.](https://github.com/neon-bindings/neon/issues/455)

I looked at that issue multiple times - but not really having much understanding of rust I couldn't sort it out. What's odd is the differences between the cli tool version and then the dependancies versions don't seem to be linked. That issue you reference even says someone went to neon-cli@0.3.1 which resolved the issue for them which seems confusing to me as the issue states you need 0.3.2 for it to work? I guess the tools and the library are just different but it's unfortunate that the versions numbers are similar confusing matters?

**Comment by greg-n** [comment]
Yeah idk. I guess the cli tool might have different versioning or can get out of sync from the rust creates. Definitely a weird quark.

**Comment by pitaj** [comment]
I'll bump the rust dependencies including neon this week. Thanks for figuring it out, as I do not have a Mac.

**Comment by jedimonkey** [comment]
All good, glad I could help! What really threw me was when I got finally it compiling it was slower than the JS version! I wasn't using `--release` and after adding it to the compile the rust version sped up about 4-5 times. I haven't seen the 30x speed increase over the JS, but it's certainly faster (~15s down to 5.5s) to build templates in NodeBB.

**Comment by pitaj** [comment]
The actual build times are dominated by uglify minifying the generated js module templates. Which is why you don't see the 30x increase.

**Comment by pitaj** [comment]
I've updated dependencies to latest in 2.0.3, so that should now work
